# -*- coding: utf-8 -*-
"""task -3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDosNj6QKfCpnmiNhBCTwq7e2sTa_tPL
"""

import random

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (user_choice == 'rock' and computer_choice == 'scissors') or \
         (user_choice == 'scissors' and computer_choice == 'paper') or \
         (user_choice == 'paper' and computer_choice == 'rock'):
        return "You win!"
    else:
        return "You lose!"

def play_again():
    return input("Do you want to play again? (yes/no): ").lower().startswith('y')

def display_score(user_score, computer_score):
    print(f"Score - You: {user_score}, Computer: {computer_score}")

def main():
    user_score = 0
    computer_score = 0

    print("Welcome to Rock-Paper-Scissors Game!")

    while True:
        user_choice = input("Choose rock, paper, or scissors: ").lower()
        if user_choice not in ['rock', 'paper', 'scissors']:
            print("Invalid choice. Please choose rock, paper, or scissors.")
            continue

        computer_choice = random.choice(['rock', 'paper', 'scissors'])

        print(f"\nYou chose {user_choice}. Computer chose {computer_choice}.\n")

        result = determine_winner(user_choice, computer_choice)
        print(result)

        if 'win' in result:
            user_score += 1
        elif 'lose' in result:
            computer_score += 1

        display_score(user_score, computer_score)

        if not play_again():
            print("Thanks for playing. Goodbye!")
            break

if __name__ == "__main__":
    main()